### ISSUE TITLE
conda installed Keras ignores  KERAS_BACKEND value set in user's keras.json file

### ISSUE THREAD

**Issue by themantalope** [conda-forge/keras-feedstock#13]
Hi,

I would like to know why in the `activate.sh` script, the `KERAS_BACKEND` environment variable is automatically set for both Mac OS X and Linux environments. In particular on my machine I have a Mac OS X with an AMD card that can interface with Theano and OpenCL.

Sure, I can manually set my `KERAS_BACKEND` environment variable, but it seems Keras provides a convenient way to set this variable within the `$HOME/.keras/keras.json` file.

I would suggest either removing the conda `activate.sh` script or checking to see if the user has set the `KERAS_BACKEND` variable within their `$HOME/.keras/keras.json` file before overriding their preferences. At the very least, the user should be given warnings about this configuration during installation or activation.

Please see my [stackoverflow post](http://stackoverflow.com/questions/43054687/keras-ignoring-values-in-home-keras-keras-json-file/43154999#43154999) for additional details pertaining to my exact problem/setup.

**Comment by ericdill** [comment]
Seems like @jakirkham [agrees with you about setting environmental variables](https://github.com/conda-forge/keras-feedstock/pull/6#issuecomment-281456369). I have little knowledge of the relationship between keras/tensorflow/theano. Feel free to make a PR with the changes @jakirkham suggested in the linked comment above. I'm sure the community is happy to discuss solutions to your (and many other users') problem here.

**Comment by jakirkham** [comment]
Thanks for your work in this direction, @themantalope. Have added some changes to PR ( https://github.com/conda-forge/keras-feedstock/pull/25 ), which should address this issue.
