### ISSUE TITLE
Keras Version Outdated

### ISSUE THREAD

**Issue by Ninad998** [conda-forge/keras-feedstock#2]
The Keras version hosted is currently outdated. Is there going to be a new release soon?

Reference:
https://github.com/fchollet/keras#keras-deep-learning-library-for-tensorflow-and-theano

**Comment by ericdill** [comment]
@Ninad998 it is straightforward to do the update. Would you like to contribute the necessary changes to the recipe to build the new version of keras? I'm happy to walk you through the process.

**Comment by Ninad998** [comment]
@ericdill I am a little busy now a days so I'm not too sure if I will have the time, I was hoping to use the latest Keras and found that the 1.1.0 is under a pull request but the build is failing on that.
https://github.com/conda-forge/keras-feedstock/pull/1

**Comment by ericdill** [comment]
Alright no worries.  At any point in the future if you'd like me to walk you through the process, just ping me. 

Thanks for reminding me about #1. I'll see if I can't get that building

**Comment by ghego** [comment]
Hey guys, I opened #4 to update to the most recent version in keras but it seems to have trouble running the ci suite. @ericdill can you have a look at what's going on?

**Comment by jakirkham** [comment]
I think the issue was we needed a newer `tensorflow`. Maybe wait until that is fully released and then give it another go.

**Comment by ghego** [comment]
Tensorflow 0.11 has just been merged in https://github.com/conda-forge/tensorflow-feedstock/pull/22
However I'm afraid the issue has to do with this: https://github.com/conda-forge/tensorflow-feedstock/issues/19, which seems to be still open.

**Comment by ericdill** [comment]
@ghego rebase your PR and push it again to trigger the CIs again now that new tensorflow is available on anaconda.org/conda-forge

**Comment by jakirkham** [comment]
> The problem is related to the build system used to run the tests, not to the update itself. Can anyone of the maintainers of the CI system fix it?

Not sure what you are proposing. Bumping the GLIBC version in the image? That's not exactly trivial and would be a larger org discussion. Not saying it is impossible, but it is not the easiest path forward and is likely to run into obstacles.

We have gotten `keras` to work with this binary repackaging of `tensorflow` before even with the older GLIBC use at conda-forge. I would think it should be possible again. One will just need a newer GLIBC to use either of these. Have restarted the CIs on that PR to see.

If that's not working, it might be worth trying to build tensorflow from source again. Something we want to do anyways. A fair bit of work has already gone into that.

**Comment by Ninad998** [comment]
Hi,
There is still an issue with the Keras version on Conda for Windows 64-bit Python 2.

![2017-03-17](https://cloud.githubusercontent.com/assets/14342032/24028254/6fc3be62-0b08-11e7-9614-f1dc49a209ff.png)

**Comment by croth1** [comment]
I had troubles building keras on windows. Unfortunately, I don't have access to a windows machine to solve the problems. I am dependent on a windows savvy person to help me fixing the problems.

See the discussion in https://github.com/conda-forge/keras-feedstock/pull/6.

**Comment by jakirkham** [comment]
I think the problem should be resolvable if you are willing to contribute @Ninad998. 😉

**Comment by Ninad998** [comment]
Actually I think the problem should be solved on Keras's end. Since the default requirement is Tensorflow and Tensorflow does not have a Python2 PyPi install for Windows.

I will raise an issue on Keras Github.

**Comment by jakirkham** [comment]
Ok, let us know how it goes.

Though still open to a PR that does the same thing on Windows that we do on Unix, should it be needed.

**Comment by VanitarNordic** [comment]
You can use  `conda install -c hesi_m keras ` to install the latest version of Keras (2.1.6) and Tensorflow(1.8) for you. Unfortunately some Anaconda packages are outdated and people have to install them by the `Pip` which causes package conflicts with the conda and pip.

**Comment by jakirkham** [comment]
We are currently on 2.1.5 and there is a PR open for 2.1.6. The community is welcome to push this forward and take a more active roll in this and other feedstocks if they are of interest.
