### ISSUE TITLE
Limiting tensorflow to <=1.0.0 on OS X

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/keras-feedstock#21]
The recipe currently puts an upper bound on the TensorFlow package via the `- tensorflow <=1.0.1  # [osx]` line.  As far as I am aware Keras does not have an upper bound on the version of TensorFlow it is compatible with.  Does this limitation need to be retained?

**Comment by mariusvniekerk** [comment]
we can always try and build it with a higher version

**Comment by jakirkham** [comment]
cc @croth1

**Comment by croth1** [comment]
IIRC, this was not a problem of keras needing a special TF version, but rather the TF build at that time being (binary?) incompatible with keras. I don't recall the details, however.
I think it would be worthwhile to investigate whether this is still needed.

**Comment by EelcoHoogendoorn** [comment]
Yeah, it would be great if this were re-examined. Currently, one is force to choose between either an ancient tensorflow or ancient keras on OSX; would be a shame if that was for nothing.

**Comment by EelcoHoogendoorn** [comment]
For the record; I just checked and the anaconda keras package has no such constraint; but it recieves far less traffic than the conda-forge one; so maybe its just a less-well considered package?

**Comment by jakirkham** [comment]
Well there’s an update PR that could be taken over and used to fix these issues. Want to give it a try, @EelcoHoogendoorn?

**Comment by jakirkham** [comment]
Have added some changes on top of PR ( https://github.com/conda-forge/keras-feedstock/pull/25 ), which relax the `tensorflow` version constraint. Please take a look and share your thoughts.
