### ISSUE TITLE
Keras 3.0 coming up with multiple backends (tf, pytorch, jax)

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/keras-feedstock#69]
Pointed out in the tf 2.15 [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.15.0-rc1), which says
> This will be the final release before the launch of Keras 3.0, when Keras will become multi-backend. For the compatibility page and other info, please see: https://github.com/keras-team/keras-core

FYI @conda-forge/keras @conda-forge/tensorflow @conda-forge/pytorch-cpu @conda-forge/jax @conda-forge/jaxlib

**Comment by xhochy** [comment]
Yes
